const news = {
    "status": "success",
    "totalResults": 1819,
    "results": [
        {
            "article_id": "1e1a7a621eb4a7ff151e9155696ef6f7",
            "title": "Israeli drone strike kills Palestinian gunmen amid more West Bank raids",
            "link": "https://www.channelnewsasia.com/world/israeli-drone-strike-kills-palestinian-gunmen-amid-more-west-bank-raids-4589306",
            "keywords": [
                "world"
            ],
            "creator": null,
            "video_url": null,
            "description": null,
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-05 20:22:00",
            "pubDateTZ": "UTC",
            "image_url": "https://onecms-res.cloudinary.com/image/upload/s--KLNZh8eo--/c_fill,h_900,w_1600/fl_relative,g_south_east,l_one-cms:core:watermark:ap_data-1,w_0.1/f_auto,q_auto/v1/one-cms/core/aptopix_israel_palestinians_32169.jpg?itok=Z6xpzVVC",
            "source_id": "channelnewsasia",
            "source_priority": 37829,
            "source_name": "Cna",
            "source_url": "https://www.channelnewsasia.com",
            "source_icon": "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
            "language": "english",
            "country": [
                "georgia",
                "yemen",
                "afghanistan",
                "cyprus",
                "india",
                "singapore",
                "saudi arabia",
                "maldives",
                "japan",
                "united arab emirates",
                "malaysia",
                "china",
                "south korea",
                "north korea",
                "taiwan",
                "thailand",
                "pakistan",
                "mongolia",
                "brunei",
                "lebanon",
                "indonesia",
                "kyrgyzstan",
                "syria",
                "israel",
                "bhutan",
                "iran",
                "turkey",
                "armenia",
                "qatar",
                "philippines",
                "hong kong",
                "kazakhstan",
                "iraq",
                "bangladesh",
                "laos",
                "vietnam",
                "timor-leste",
                "kuwait",
                "myanmar",
                "azerbaijan",
                "jordan",
                "nepal",
                "sri lanka",
                "uzbekistan",
                "turkmenistan",
                "macau",
                "bahrain",
                "cambodia",
                "tajikistan"
            ],
            "category": [
                "world"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": true
        },
        {
            "article_id": "4fa9d44b7cbc9da6ccc3f6549a1c18e0",
            "title": "Broadcom raises annual AI revenue estimate on demand for custom chips",
            "link": "https://www.channelnewsasia.com/business/broadcom-raises-annual-ai-revenue-estimate-demand-custom-chips-4589816",
            "keywords": [
                "business"
            ],
            "creator": null,
            "video_url": null,
            "description": null,
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-05 20:20:14",
            "pubDateTZ": "UTC",
            "image_url": "https://onecms-res.cloudinary.com/image/upload/s--7NR5XmKj--/c_fill,h_900,w_1600/fl_relative,g_south_east,l_mediacorp:cna:watermark:2024-04:reuters_1,w_0.1/f_auto,q_auto/v1/one-cms/core/2024-09-05t202014z_1_lynxmpek840xa_rtroptp_3_broadcom-results.jpg?itok=1vevtC9s",
            "source_id": "channelnewsasia",
            "source_priority": 37829,
            "source_name": "Cna",
            "source_url": "https://www.channelnewsasia.com",
            "source_icon": "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
            "language": "english",
            "country": [
                "singapore",
                "georgia",
                "yemen",
                "afghanistan",
                "cyprus",
                "india",
                "saudi arabia",
                "maldives",
                "japan",
                "united arab emirates",
                "malaysia",
                "china",
                "south korea",
                "north korea",
                "taiwan",
                "thailand",
                "pakistan",
                "mongolia",
                "brunei",
                "lebanon",
                "indonesia",
                "kyrgyzstan",
                "syria",
                "israel",
                "bhutan",
                "iran",
                "turkey",
                "armenia",
                "qatar",
                "philippines",
                "hong kong",
                "kazakhstan",
                "iraq",
                "bangladesh",
                "laos",
                "vietnam",
                "timor-leste",
                "kuwait",
                "myanmar",
                "azerbaijan",
                "jordan",
                "nepal",
                "oman",
                "sri lanka",
                "uzbekistan",
                "turkmenistan",
                "macau",
                "bahrain",
                "cambodia",
                "tajikistan"
            ],
            "category": [
                "business"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "5f88e8641114ae06c46feddc0174204f",
            "title": "Broadcom forecasts lukewarm quarterly revenue despite AI chip surge, shares fall",
            "link": "https://www.channelnewsasia.com/business/broadcom-forecasts-lukewarm-quarterly-revenue-despite-ai-chip-surge-shares-fall-4589816",
            "keywords": [
                "business"
            ],
            "creator": null,
            "video_url": null,
            "description": null,
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-05 20:20:14",
            "pubDateTZ": "UTC",
            "image_url": "https://onecms-res.cloudinary.com/image/upload/s--7NR5XmKj--/c_fill,h_900,w_1600/fl_relative,g_south_east,l_mediacorp:cna:watermark:2024-04:reuters_1,w_0.1/f_auto,q_auto/v1/one-cms/core/2024-09-05t202014z_1_lynxmpek840xa_rtroptp_3_broadcom-results.jpg?itok=1vevtC9s",
            "source_id": "channelnewsasia",
            "source_priority": 37829,
            "source_name": "Cna",
            "source_url": "https://www.channelnewsasia.com",
            "source_icon": "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
            "language": "english",
            "country": [
                "singapore",
                "georgia",
                "yemen",
                "afghanistan",
                "cyprus",
                "india",
                "saudi arabia",
                "maldives",
                "japan",
                "united arab emirates",
                "malaysia",
                "china",
                "south korea",
                "north korea",
                "taiwan",
                "thailand",
                "pakistan",
                "mongolia",
                "brunei",
                "lebanon",
                "indonesia",
                "kyrgyzstan",
                "syria",
                "israel",
                "bhutan",
                "iran",
                "turkey",
                "armenia",
                "qatar",
                "philippines",
                "hong kong",
                "kazakhstan",
                "iraq",
                "bangladesh",
                "laos",
                "vietnam",
                "timor-leste",
                "kuwait",
                "myanmar",
                "azerbaijan",
                "jordan",
                "nepal",
                "oman",
                "sri lanka",
                "uzbekistan",
                "turkmenistan",
                "macau",
                "bahrain",
                "cambodia",
                "tajikistan"
            ],
            "category": [
                "business"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "0572dc1ed5c50fc85bd70052e87f832c",
            "title": "“อิเหนา” ฟอร์มแกร่งบุกแบ่งแต้ม “ซาอุฯ” คัดบอลโลกโซนเอเชีย",
            "link": "https://www.dailynews.co.th/news/3832262/",
            "keywords": null,
            "creator": [
                "ประพนธ์ ปัญหา"
            ],
            "video_url": null,
            "description": "\"อินโดนีเซีย\" ฟอร์มแกร่ง หลังบุกเจ๊า \"ซาอุดีอาระเบีย\" ถึงบ้าน 1-1 เกมประเดิมสนามฟุตบอลโลก 2026 รอบคัดเลือก โซนเอเชีย รอบ 3The post “อิเหนา” ฟอร์มแกร่งบุกแบ่งแต้ม “ซาอุฯ” คัดบอลโลกโซนเอเชีย appeared first on เดลินิวส์.",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-05 20:18:40",
            "pubDateTZ": "UTC",
            "image_url": null,
            "source_id": "dailynews_co_th",
            "source_priority": 425309,
            "source_name": "Dailynews Co Th",
            "source_url": "https://www.dailynews.co.th",
            "source_icon": "https://i.bytvi.com/domain_icons/dailynews_co_th.png",
            "language": "thai",
            "country": [
                "thailand"
            ],
            "category": [
                "sports"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "84abda1dac00494ddc1b0d97999fe9b6",
            "title": "มาครงเสนอชื่อ มิเชล มาร์นิเยร์ เป็นนายกฯ คนใหม่ หวังคลายล็อกการเมือง",
            "link": "https://www.thairath.co.th/news/foreign/2812802",
            "keywords": null,
            "creator": null,
            "video_url": null,
            "description": "เอ็มมานูเอล มาครง เสนอชื่อนาย มิเชล บาร์นิเยร์ เป็นนายกรัฐมนตรีคนใหม่ของประเทศ หวังคลายล็อกทางการเมืองที่เกิดขึ้นหลังการเลือกตั้งเมื่อ 2 เดือนก่อน",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-05 20:12:00",
            "pubDateTZ": "UTC",
            "image_url": "https://static.thairath.co.th/media/CiHZjUdJ5HPNXJ92O0egjUt0EvbdvQvxot.jpg",
            "source_id": "thairath",
            "source_priority": 44507,
            "source_name": "Thairath",
            "source_url": "https://www.thairath.co.th",
            "source_icon": "https://i.bytvi.com/domain_icons/thairath.png",
            "language": "thai",
            "country": [
                "thailand"
            ],
            "category": [
                "top"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "e65fcc39bf43be7c7c52817fcca988a9",
            "title": "CBOE partners with UK firm to launch US private share trading platform, Bloomberg News reports",
            "link": "https://www.channelnewsasia.com/business/cboe-partners-uk-firm-launch-us-private-share-trading-platform-bloomberg-news-reports-4589781",
            "keywords": [
                "business"
            ],
            "creator": null,
            "video_url": null,
            "description": null,
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-05 20:08:09",
            "pubDateTZ": "UTC",
            "image_url": "https://onecms-res.cloudinary.com/image/upload/s--ZE7HwTrO--/c_fill,h_900,w_1600/fl_relative,g_south_east,l_mediacorp:cna:watermark:2024-04:reuters_1,w_0.1/f_auto,q_auto/v1/one-cms/core/2024-09-05t200809z_2_lynxmpek840s1_rtroptp_3_global-short-vol.jpg?itok=3OPHvJN0",
            "source_id": "channelnewsasia",
            "source_priority": 37829,
            "source_name": "Cna",
            "source_url": "https://www.channelnewsasia.com",
            "source_icon": "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
            "language": "english",
            "country": [
                "singapore",
                "georgia",
                "yemen",
                "afghanistan",
                "cyprus",
                "india",
                "saudi arabia",
                "maldives",
                "japan",
                "united arab emirates",
                "malaysia",
                "china",
                "south korea",
                "north korea",
                "taiwan",
                "thailand",
                "pakistan",
                "mongolia",
                "brunei",
                "lebanon",
                "indonesia",
                "kyrgyzstan",
                "syria",
                "israel",
                "bhutan",
                "iran",
                "turkey",
                "armenia",
                "qatar",
                "philippines",
                "hong kong",
                "kazakhstan",
                "iraq",
                "bangladesh",
                "laos",
                "vietnam",
                "timor-leste",
                "kuwait",
                "myanmar",
                "azerbaijan",
                "jordan",
                "nepal",
                "oman",
                "sri lanka",
                "uzbekistan",
                "turkmenistan",
                "macau",
                "bahrain",
                "cambodia",
                "tajikistan"
            ],
            "category": [
                "business"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "5fc24b1b0b39f26ea73c6efdb7b39f27",
            "title": "Slipper set to equal Australia caps record against Argentina",
            "link": "https://www.channelnewsasia.com/sport/slipper-set-equal-australia-caps-record-against-argentina-4589786",
            "keywords": [
                "sport"
            ],
            "creator": null,
            "video_url": null,
            "description": null,
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-05 20:07:13",
            "pubDateTZ": "UTC",
            "image_url": "https://onecms-res.cloudinary.com/image/upload/s--mSxl6COu--/c_fill,h_900,w_1600/fl_relative,g_south_east,l_mediacorp:cna:watermark:2024-04:reuters_1,w_0.1/f_auto,q_auto/v1/one-cms/core/2024-09-05t200713z_1_lynxmpek840x0_rtroptp_3_rugby-union-wal-aus.jpg?itok=OnXZRIvq",
            "source_id": "channelnewsasia",
            "source_priority": 37829,
            "source_name": "Cna",
            "source_url": "https://www.channelnewsasia.com",
            "source_icon": "https://i.bytvi.com/domain_icons/channelnewsasia.jpg",
            "language": "english",
            "country": [
                "singapore",
                "georgia",
                "yemen",
                "afghanistan",
                "cyprus",
                "india",
                "saudi arabia",
                "maldives",
                "japan",
                "united arab emirates",
                "malaysia",
                "china",
                "south korea",
                "north korea",
                "taiwan",
                "thailand",
                "pakistan",
                "mongolia",
                "brunei",
                "lebanon",
                "indonesia",
                "kyrgyzstan",
                "syria",
                "israel",
                "bhutan",
                "iran",
                "turkey",
                "armenia",
                "qatar",
                "philippines",
                "hong kong",
                "kazakhstan",
                "iraq",
                "bangladesh",
                "laos",
                "vietnam",
                "timor-leste",
                "kuwait",
                "myanmar",
                "azerbaijan",
                "jordan",
                "nepal",
                "oman",
                "sri lanka",
                "uzbekistan",
                "turkmenistan",
                "macau",
                "bahrain",
                "cambodia",
                "tajikistan"
            ],
            "category": [
                "sports"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "6e2931414711860c1dcfc961465eefc8",
            "title": "รวบสองพี่น้องฉายา ‘เจ้าทศกัณฐ์’ ปล่อยกู้ดอกโหด เงินหมุนเวียน 2 ล้านต่อเดือน",
            "link": "https://www.dailynews.co.th/news/3831929/",
            "keywords": [
                "hot news",
                "breakingnews"
            ],
            "creator": [
                "Sutannaraj Suwannatada"
            ],
            "video_url": null,
            "description": "รวบคาบ้านสองพี่น้อง ฉายา \"เจ้าทศกัณฐ์ เงินกู้\" ปล่อยกู้ดอกเบี้ยโหด ร้อยละ 30 บาทต่อเดือน วงเงินหมุนเวียนประมาณ 2 ล้านบาทต่อเดือน ค้นบ้านพบหลักฐาน และอาวุธปืนThe post รวบสองพี่น้องฉายา ‘เจ้าทศกัณฐ์’ ปล่อยกู้ดอกโหด เงินหมุนเวียน 2 ล้านต่อเดือน appeared first on เดลินิวส์.",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-05 20:00:00",
            "pubDateTZ": "UTC",
            "image_url": null,
            "source_id": "dailynews_co_th",
            "source_priority": 425309,
            "source_name": "Dailynews Co Th",
            "source_url": "https://www.dailynews.co.th",
            "source_icon": "https://i.bytvi.com/domain_icons/dailynews_co_th.png",
            "language": "thai",
            "country": [
                "thailand"
            ],
            "category": [
                "other"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "d6205e8948462fb4358c63b7d4665cc8",
            "title": "Dragon Age: The Veilguard's Devs Reveal New Info About Each of the Companions (and Solas and Varric, Too)",
            "link": "https://sea.ign.com/dragon-age-dreadwolf/220250/preview/dragon-age-the-veilguards-devs-reveal-new-info-about-each-of-the-companions-and-solas-and-varric-too",
            "keywords": [
                "dragon age: dreadwolf",
                "preview"
            ],
            "creator": [
                "Alex Stedman"
            ],
            "video_url": null,
            "description": "It turns out The Veilguard really is the friends we made along the way.Friendships, romantic relationships, and everything in between have always been an integral part of not just the Dragon Age series, but of BioWare in general. From Mass Effect’s Garrus Vakarian to Dragon Age’s Varric Tethras, the characters – and how they get along with the player – are inseparable from ...",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-05 19:59:49",
            "pubDateTZ": "UTC",
            "image_url": "https://sm.ign.com/ign_ap/preview/d/dragon-age/dragon-age-the-veilguards-devs-reveal-new-info-about-each-of_ksuy.jpg",
            "source_id": "ign",
            "source_priority": 144,
            "source_name": "Ign Southeast Asia",
            "source_url": "https://sea.ign.com",
            "source_icon": "https://i.bytvi.com/domain_icons/ign.png",
            "language": "english",
            "country": [
                "vietnam",
                "singapore",
                "malaysia",
                "myanmar",
                "philippines",
                "thailand",
                "brunei",
                "indonesia",
                "cambodia"
            ],
            "category": [
                "top"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        },
        {
            "article_id": "337043c9d44904da3ccb8f1766b45221",
            "title": "“เศรษฐีนี”เผยเจ้าวัดดังยอมใช้หนี้ ทําข้อตกลงจะไม่ให้ข่าวต่อสื่อฯ",
            "link": "https://www.dailynews.co.th/news/3832249/",
            "keywords": [
                "hot news",
                "breakingnews"
            ],
            "creator": [
                "Tanomsri Jantong"
            ],
            "video_url": null,
            "description": "เมื่อวันที [...]The post “เศรษฐีนี”เผยเจ้าวัดดังยอมใช้หนี้ ทําข้อตกลงจะไม่ให้ข่าวต่อสื่อฯ appeared first on เดลินิวส์.",
            "content": "ONLY AVAILABLE IN PAID PLANS",
            "pubDate": "2024-09-05 19:55:48",
            "pubDateTZ": "UTC",
            "image_url": null,
            "source_id": "dailynews_co_th",
            "source_priority": 425309,
            "source_name": "Dailynews Co Th",
            "source_url": "https://www.dailynews.co.th",
            "source_icon": "https://i.bytvi.com/domain_icons/dailynews_co_th.png",
            "language": "thai",
            "country": [
                "thailand"
            ],
            "category": [
                "other"
            ],
            "ai_tag": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "sentiment_stats": "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            "ai_region": "ONLY AVAILABLE IN CORPORATE PLANS",
            "ai_org": "ONLY AVAILABLE IN CORPORATE PLANS",
            "duplicate": false
        }
    ],
    "nextPage": "1725566148887924708"
}

const thaiNews = news.results.filter(function(element, index) {
    return element.language === 'thai'
})

console.log('filter with for loop: ', thaiNews)